In [4]:
import numpy as np

In [6]:
dir(np)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_CopyMode',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__deprecated_attrs__',
 '__dir__',
 '__doc__',
 '__expired_functions__',
 '__file__',
 '__former_attrs__',
 '__future_scalars__',
 '__getattr__',
 '__git_version__',
 '__loader__',

In [7]:
#create 1D numpy array
x = np.array([45,67,80,90])
print(x)
print(type(x))
print(x.dtype)


[45 67 80 90]
<class 'numpy.ndarray'>
int32


In [8]:
#Verify the data type
x = np.array(["A",67,80,9.5])
print(x)
print(type(x))
print(x.dtype)


['A' '67' '80' '9.5']
<class 'numpy.ndarray'>
<U32


In [9]:
#Create a 2D Array
a2 = np.array([[20,50], [40,90]])
print(a2)
print(type(a2))
print(a2.shape)


[[20 50]
 [40 90]]
<class 'numpy.ndarray'>
(2, 2)


In [16]:
#Reshaping an array using reshape()
#possible only (1,4), (4,1), (2,2)
a = np.array([10,20,30,40])
b = a.reshape(2,2)
print(b)
print(b.shape)

[[10 20]
 [30 40]]
(2, 2)


In [11]:
#Reshaping an array using reshape()
a = np.array([10,20,30,40])
b = a.reshape(1,4)
print(b)
print(b.shape)

[[10 20 30 40]]
(1, 4)


In [15]:
#Reshaping an array using reshape()
a = np.array([10,20,30,40])
b = a.reshape(4,1)
print(b)
print(b.shape)

[[10]
 [20]
 [30]
 [40]]
(4, 1)


In [18]:
#Create an array with arange()
c = np.arange(3,10)
print(c)
type(c)


[3 4 5 6 7 8 9]


numpy.ndarray

In [20]:
#Create an array with arange()
c = np.arange(4,14)
print(c)
type(c)


[ 4  5  6  7  8  9 10 11 12 13]


numpy.ndarray

In [23]:
#Use of around() its meant for adjusting decimal numbers
d = np.array([1.3467, 3.10987, 4.91236])
print(d)
np.around(d,2)

[1.3467  3.10987 4.91236]


array([1.35, 3.11, 4.91])

In [25]:
#Use of np.sqrt()
d = np.array([1.3456, 5.9087, 67.456])
print(d)
print(np.around(np.sqrt(d),2))

[ 1.3456  5.9087 67.456 ]
[1.16 2.43 8.21]


In [33]:
#Create a 2D array(NaN stands for not a number)it means to identify missing value
a1 = np.array([[3,4,5,6],[7,2,8,np.NaN]])
print(a1)
a1.dtype

[[ 3.  4.  5.  6.]
 [ 7.  2.  8. nan]]


dtype('float64')

In [36]:
#Use of astype() to convert the data type
a1 = np.array([[3,4,5,8], [7,2,8,np.NaN]])
a1_copy1 = a1.astype(str)
print(a1_copy1)
a1_copy1.dtype

[['3.0' '4.0' '5.0' '8.0']
 ['7.0' '2.0' '8.0' 'nan']]


dtype('<U32')

In [37]:
#Use of astype() to convert the data type
a1 = np.array([[3,4,5,8], [7,2,8,np.NaN]])
a1_copy1 = a1.astype(float)
print(a1_copy1)
a1_copy1.dtype

[[ 3.  4.  5.  8.]
 [ 7.  2.  8. nan]]


dtype('float64')

In [43]:
#Mathematical operations on rows and cols
a2 = np.array([[3,4,5],[6,7,8],[9,10,11]])
a2

array([[ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [44]:
#Adding row wise
a2 = np.array([[3,4,5],[6,7,8],[9,10,11]])
a2.sum(axis=1)

array([12, 21, 30])

In [45]:
#Assing column wise
a2 = np.array([[3,4,5],[6,7,8],[9,10,11]])
a2.sum(axis=0)

array([18, 21, 24])

In [46]:
#Average
a2 = np.array([[3,4,5],[6,7,8],[9,10,11]])
a2.mean()

7.0

In [47]:
#Matrix Operations
a3 = np.array([[2,3,4], [4,5,6], [7,8,9]])
a3

array([[2, 3, 4],
       [4, 5, 6],
       [7, 8, 9]])

In [50]:
#Matrix Operations
a3 = np.array([[2,3,4,5], [4,5,6,1], [7,8,9,2],[1,2,3,4]])
a3

array([[2, 3, 4, 5],
       [4, 5, 6, 1],
       [7, 8, 9, 2],
       [1, 2, 3, 4]])

In [55]:
#Set diagonal with 0
np.fill_diagonal(a3,0)
print(a3)

[[0 3 4]
 [4 0 6]
 [7 8 0]]


In [56]:
#Set diagonal with 1
np.fill_diagonal(a3,1)
print(a3)

[[1 3 4]
 [4 1 6]
 [7 8 1]]
